/* Sample organizations (fictional). fit = adults, problem, size, hiring, decider, vendors, buying, warm (y / n / ?) */
export const CATALOG = [
 {key:"kestrel", name:"Kestrel Aerostructures", sector:"Manufacturing", size:"~1,800 staff", region:"Western Canada", signals:["reskilling","pipeline"], fit:"yyyy?yy?", hiring:"~40 open roles, incl. 6 apprenticeships (sample)",
  summary:"Aircraft-parts manufacturer automating its machining lines and running an apprenticeship program.",
  analysis:{problems:[{title:"Reskilling",detail:"Automation is changing machinist roles; some staff need a path into programming, inspection or maintenance."},{title:"Workforce pipeline",detail:"Apprentices choose a trade early and some drop out when it doesn't suit them."}],
   evidence:[{text:"Posted six apprenticeship openings and a \"Workforce Development Coordinator\" role.",source:"Job postings (sample)"},{text:"Announced a two-year automation upgrade of its main plant.",source:"News release (sample)"},{text:"Training budget is managed by a single L&D lead.",source:"LinkedIn (sample)"}],
   unknowns:["Does the L&D lead have budget authority for new tools?","How many apprentices leave in their first year?"],
   roles:["Workforce Development Coordinator","Manager, Learning & Development","VP Operations"],
   fitConcerns:["Manufacturing staff may prefer hands-on assessments to an online sandbox."]}},
 {key:"prairiehealth", name:"Prairie Health Network", sector:"Healthcare employer", size:"~6,000 staff", region:"Western Canada", signals:["retention","pipeline"], fit:"yyyy?y??", hiring:"~120 open roles (sample)",
  summary:"Regional health employer with ongoing turnover in nursing and allied-health roles.",
  analysis:{problems:[{title:"Employee retention",detail:"First-year turnover in frontline roles is costly; staff who feel stuck leave for other employers."},{title:"Workforce pipeline",detail:"They need to steer existing staff toward hard-to-fill roles rather than only hiring externally."}],
   evidence:[{text:"Posted a job for a \"Retention and Engagement Specialist\".",source:"Job posting (sample)"},{text:"Announced an internal mobility program for support staff moving into clinical roles.",source:"News release (sample)"},{text:"Local news coverage of nurse turnover in rural sites.",source:"News article (sample)"}],
   unknowns:["Who owns the internal mobility program: HR, Learning & Development, or a clinical department?","Is there funding attached to the retention role?","Would a union need to be consulted?"],
   roles:["VP People & Culture","Director, Learning & Development","Retention and Engagement Specialist (influencer)"],
   fitConcerns:["Large employer: the first person reached may not have authority.","Health systems may prefer tools already in their HR platform."]}},
 {key:"fieldstone", name:"Fieldstone Home Care", sector:"Home and community care", size:"~350 caregivers", region:"Prairies", signals:["retention","transitions"], fit:"yyyy?y??", hiring:"~25 open roles (sample)",
  summary:"Home-care provider that loses many new caregivers within their first year.",
  analysis:{problems:[{title:"Employee retention",detail:"Caregivers often take the job as a stopgap and leave when they find a better-fitting path."},{title:"Career transitions",detail:"Many hires are career changers who haven't explored whether care work suits them."}],
   evidence:[{text:"Careers page says \"no experience needed\" and recruits career changers.",source:"Website (sample)"},{text:"Posts the same caregiver openings every month.",source:"Job postings (sample)"}],
   unknowns:["What is their actual first-year turnover?","Does the owner or an HR manager decide on tools?"],
   roles:["Director of Operations","HR Manager"],
   fitConcerns:["Thin margins may limit budget."]}},
 {key:"summitcu", name:"Summit Credit Union", sector:"Financial services", size:"~700 staff", region:"Prairies", signals:["retention","transitions"], fit:"yyyy?y??", hiring:"~15 open roles (sample)",
  summary:"Regional credit union consolidating branches and moving tellers into advisory and digital roles.",
  analysis:{problems:[{title:"Employee retention",detail:"Branch consolidation can push experienced staff to leave if they don't see a future role."},{title:"Career transitions",detail:"Tellers are being asked to move into advisory or digital-support work that may not suit everyone."}],
   evidence:[{text:"Posted a \"Career Pathing Lead\" role in HR.",source:"Job posting (sample)"},{text:"Closed three branches and opened a member contact centre.",source:"Member newsletter (sample)"}],
   unknowns:["Has the Career Pathing Lead been hired, and what tools do they plan to use?","Is there a budget line for internal mobility?"],
   roles:["Career Pathing Lead","Director of People","Chief Operating Officer"],
   fitConcerns:["May already use a career-pathing feature in their HR software."]}},
 {key:"northgate", name:"Northgate Polytechnic, Continuing Education", sector:"Post-secondary", size:"~4,000 adult learners a year", region:"Western Canada", signals:["transitions","reskilling"], fit:"yyy??yn?", hiring:"Few postings; growth is in new programs",
  summary:"Continuing-education division serving mid-career adults who enroll to change or upgrade careers.",
  analysis:{problems:[{title:"Career transitions",detail:"Adult learners often enroll without a clear target role, which can lead to program switching or non-completion."},{title:"Reskilling",detail:"New short credentials show demand from workers who need to retrain, but choosing the right credential is left to the learner."}],
   evidence:[{text:"Launched four new micro-credential programs aimed at working adults this year.",source:"Program announcements (sample)"},{text:"Career-advising page lists two advisors for the whole continuing-education division.",source:"Website (sample)"},{text:"Program pages tell learners to explore their options first, but offer no tool for it.",source:"Website (sample)"}],
   unknowns:["Does continuing education have its own budget for learner-support tools?","Who owns career advising for CE learners: the division or central career services?","Do they track non-completion, and is it a concern?"],
   roles:["Director of Continuing Education","Manager, Learner Success","Career Services Manager"],
   fitConcerns:["Post-secondary buying is slow: a stakeholder already cited bureaucracy, budget and long timelines.","Career services may see this as overlapping with existing advising."]}},
 {key:"westbrook", name:"Westbrook College", sector:"Post-secondary", size:"~9,000 students", region:"Western Canada", signals:["transitions","pipeline"], fit:"yyy??yn?", hiring:"~10 open roles (sample)",
  summary:"College where many first-year students switch out of health and business programs.",
  analysis:{problems:[{title:"Career transitions",detail:"Students switching programs cost tuition and time, and lower completion rates."},{title:"Workforce pipeline",detail:"Health programs lose students who might have stayed with better early exploration."}],
   evidence:[{text:"Annual report lists program-transfer rates as a focus for next year.",source:"Annual report (sample)"},{text:"Runs a first-year \"Explore\" seminar with no assessment tool.",source:"Website (sample)"}],
   unknowns:["Which office owns retention: student services or the academic deans?","How long does a new tool take to approve?"],
   roles:["Director, Student Success","Dean of Health","Career Centre Manager"],
   fitConcerns:["Same buying-process risk as other post-secondary institutions."]}},
 {key:"cedarvalley", name:"Cedar Valley Workforce Services", sector:"Non-profit employment services", size:"~60 staff, ~1,500 clients a year", region:"Western Canada", signals:["transitions","pipeline"], fit:"yyn??yy?", hiring:"Few postings",
  summary:"Non-profit agency running government-funded programs for adults changing careers or returning to work.",
  analysis:{problems:[{title:"Career transitions",detail:"Clients are adults between careers who need to work out what direction fits before choosing training."},{title:"Workforce pipeline",detail:"Funders measure job placement, so better early direction could improve outcomes."}],
   evidence:[{text:"Runs a \"Career Decision-Making\" workshop series for adults.",source:"Program page (sample)"},{text:"Annual report highlights clients who changed direction mid-program.",source:"Annual report (sample)"}],
   unknowns:["Do program budgets allow buying a tool, or does it need funder approval?","Would counsellors use it with clients or would clients use it alone?"],
   roles:["Executive Director","Program Manager, Career Transitions","Employment Counsellor (influencer)"],
   fitConcerns:["Small organization, though it serves many adults.","Funding cycles may limit when they can buy."]}},
 {key:"aspenridge", name:"Aspen Ridge Hotels", sector:"Hospitality", size:"~1,100 staff", region:"Rocky Mountains", signals:["retention"], fit:"yyyy????", hiring:"~70 seasonal roles (sample)",
  summary:"Resort hotel group with high seasonal turnover among young adult staff.",
  analysis:{problems:[{title:"Employee retention",detail:"Seasonal staff rarely return, so the group re-hires and re-trains every year."}],
   evidence:[{text:"Advertises a \"grow your career with us\" program but few staff move into year-round roles.",source:"Website (sample)"},{text:"Posts around 70 seasonal roles each spring.",source:"Job postings (sample)"}],
   unknowns:["Is turnover seen as a problem or just a cost of seasonal work?","Who owns staff development: HR or each property?"],
   roles:["Director of Human Resources","Talent Development Manager"],
   fitConcerns:["They may accept turnover as normal for the industry."]}},
 {key:"helix", name:"Helix Energy Services", sector:"Energy services", size:"~2,400 staff", region:"Western Canada", signals:["transitions","reskilling"], fit:"yyyy??n?", hiring:"Hiring in one division, cutting in two",
  summary:"Oilfield services company restructuring as clients shift toward lower-carbon projects.",
  analysis:{problems:[{title:"Career transitions",detail:"Restructuring means some staff must move into new kinds of work or leave the company."},{title:"Reskilling",detail:"New service lines need people with different skills than the current workforce."}],
   evidence:[{text:"Announced a new division focused on carbon capture services.",source:"Investor update (sample)"},{text:"Reported workforce reductions in two field locations.",source:"News article (sample)"}],
   unknowns:["Do they offer outplacement or redeployment support today?","Is HR centralized or regional?"],
   roles:["VP Human Resources","Talent Development Lead","Outplacement / Transition Program Lead"],
   fitConcerns:["Outplacement is often bought from established firms through long procurement."]}},
 {key:"bowline", name:"Bowline Logistics", sector:"Transportation & warehousing", size:"~900 staff", region:"Prairies", signals:["reskilling","retention"], fit:"yyyy????", hiring:"~30 open roles (sample)",
  summary:"Mid-size trucking and warehousing company automating parts of its warehouses.",
  analysis:{problems:[{title:"Reskilling",detail:"Warehouse automation is changing roles; some workers need a path into maintenance, dispatch or supervision."},{title:"Employee retention",detail:"Workers who can't see a next step may leave during the transition."}],
   evidence:[{text:"Opened an automated distribution centre this year.",source:"News release (sample)"},{text:"Careers page advertises \"grow with us\" but lists no development program.",source:"Website (sample)"}],
   unknowns:["Is there an HR or training lead, or does the owner decide?","Are they building their own training ladder?"],
   roles:["HR Manager","Operations Director","Owner / President"],
   fitConcerns:["May build training in-house with their union."]}},
 {key:"ironwood", name:"Ironwood Mining", sector:"Mining", size:"~3,000 staff", region:"Northern Canada", signals:["reskilling","pipeline"], fit:"yyyy?n??", hiring:"~90 open roles (sample)",
  summary:"Large mining operator with a strong internal training academy.",
  analysis:{problems:[{title:"Workforce pipeline",detail:"Remote sites struggle to fill skilled trades roles."}],
   evidence:[{text:"Runs its own training academy and builds its programs internally.",source:"Website (sample)"},{text:"Careers site lists about 90 openings across sites.",source:"Job postings (sample)"}],
   unknowns:["Would the academy ever license an outside tool?"],
   roles:["Director, Training Academy"],
   fitConcerns:["Builds everything in-house, like an earlier contact who only used internal tools."]}},
 {key:"ridgeline", name:"Ridgeline Staffing Group", sector:"Recruitment & staffing", size:"~120 staff", region:"Western Canada", signals:["pipeline"], fit:"y?n??y??", hiring:"Recruits for clients, not itself",
  summary:"Staffing agency placing adults in light industrial and administrative roles.",
  analysis:{problems:[{title:"Workforce pipeline",detail:"Placements that don't fit the candidate end early, which costs the agency and the client."}],
   evidence:[{text:"Website promotes \"the right fit, the first time\" as a service promise.",source:"Website (sample)"}],
   unknowns:["Do they use personality in matching at all?","Who decides on candidate-assessment tools?"],
   roles:["Director of Operations","Recruitment Manager"],
   fitConcerns:["A recruiter Joan spoke with didn't use personality types in their process.","They may want a screening score, which Myrimaven does not offer."]}},
 {key:"lumen", name:"Lumen Labs", sector:"Software startup", size:"~40 staff", region:"Calgary", signals:[], fit:"ynnn?yy?", hiring:"~3 open roles (sample)",
  summary:"Small, fast-growing software company with low turnover.",
  analysis:{problems:[],
   evidence:[{text:"Staff reviews describe low turnover and clear promotion paths.",source:"Employer reviews (sample)"}],
   unknowns:["Is there any career alignment problem at all?"],
   roles:["Co-founder / CEO"],
   fitConcerns:["No sign of a career alignment problem.","Too small to need a structured tool."]}},
 {key:"brightwater", name:"Brightwater School Division", sector:"K–12 education", size:"~30 schools", region:"Prairies", signals:["pipeline"], fit:"ny?????n", outside:true, hiring:"Not checked",
  summary:"School division with a high-school career-education requirement.",
  analysis:{problems:[{title:"Workforce pipeline",detail:"Students must complete career-education courses, but exploration tools are limited."}],
   evidence:[{text:"Career and life management course is required for graduation.",source:"Curriculum page (sample)"}],
   unknowns:["Would a division buy centrally, or does each school decide?"],
   roles:["Career Education Coordinator","Assistant Superintendent, Learning"],
   fitConcerns:["About 30 cold emails to K–12 schools got no replies.","Myrimaven is focused on adults."]}},
 {key:"corbel", name:"Corbel Career Coaching", sector:"Career coaching", size:"6 coaches", region:"Calgary", signals:["transitions"], fit:"y?nn????", outside:true, hiring:"Not checked",
  summary:"Small coaching practice helping professionals change careers.",
  analysis:{problems:[{title:"Career transitions",detail:"Their clients are mid-career adults exploring new paths."}],
   evidence:[{text:"Offers one-on-one career transition packages.",source:"Website (sample)"}],
   unknowns:["Would coaches see the sandbox as a tool or as a competitor?"],
   roles:["Founder"],
   fitConcerns:["Career coaches aren't a current target; Joan expects the approach clashes with their methods, but this is untested."]}}
];
